<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE equipo [
<!ELEMENT equipo (pokemon+)>
<!ELEMENT pokemon (nombre, tipo+, nivel)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT tipo (#PCDATA)>
<!ELEMENT nivel (#PCDATA)>
]>

<equipo>
    <pokemon>
        <nombre>Glaceon</nombre>
        <tipo>hielo</tipo>
        <nivel>2</nivel>
    </pokemon>
    <pokemon>
        <nombre>Arceus</nombre>
        <tipo>normal</tipo>
        <nivel>10</nivel>
    </pokemon>
    <pokemon>
        <nombre>Cryogonal</nombre>
        <tipo>hielo</tipo>
        <nivel>5</nivel>
    </pokemon>
</equipo>