<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE curso [
<!ELEMENT curso (nombre, alumno+)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT alumno (nombre, apellido)>
<!ELEMENT apellido (#PCDATA)>
]>

<curso>
    <nombre>3ºA</nombre>
    <alumno>
        <nombre>Martín</nombre>
        <apellido>Díaz</apellido>
    </alumno>
    <alumno>
        <nombre>David</nombre>
        <apellido>Peña</apellido>
    </alumno>
</curso>
